#!/usr/bin/env expect

set timeout 30

trap {
  set rows [stty rows]
  set cols [stty columns]
  stty rows $rows columns $cols < $spawn_out(slave,name)
} WINCH

set host [lindex $argv 0]

spawn ssh jumpserver
  expect {
    "*MFA*" {
      set AUTH [exec /Users/hawtian/Projects/braum_goto/my-opt-auth.py]
      send "$AUTH\r"
      exp_continue
    }
    "*Opt*" { send "$host\r" }
  }

interact

